[package]
name = "json-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
parser-core = { path = "../parser-core" }
serde = "1.0.219"
serde_json = "1.0.140"
memmap2 = "0.9.5"
rayon = "1.10.0"
anyhow = "1.0.98"
simd-json = "0.15.1"

[dev-dependencies]
tempfile = "3.20.0"
criterion = "0.6.0"
