[workspace]
members = [
    "crates/cli",
    "crates/parser-core",
    "crates/txt-parser",
    "crates/json-parser",
    "crates/csv-parser"
, "criterion-test"]
resolver = "2"

[profile.bench]
debug = true
