[package]
name = "csv-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.5"
rayon = "1.10.0"
memchr = "2.7.5"
parser-core = { path = "../parser-core" }
libc = "0.2"

[dev-dependencies]
tempfile = "3.20.0"
criterion = "0.6.0"
