[package]
name = "csv-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.5"
rayon = "1.5"
memchr = "2.7"
parser-core = { path = "../parser-core" }
libc = "0.2"

[dev-dependencies]
tempfile = "3.10"
criterion = "0.5"
