name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build --workspace --all-targets --release
      - name: Run tests
        run: cargo test --workspace --all-features --release
      - name: Install rustfmt
        run: rustup component add rustfmt || true
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Audit dependencies
        run: cargo install cargo-audit && cargo audit || true
      - name: Build documentation
        run: cargo doc --workspace --no-deps --release
